### ISSUE TITLE
Bug: When Compose window is full, it tries to keep new text behind the toolbar

### ISSUE THREAD

**Issue by LorenAmelang** [Dimillian/IceCubesApp#656] opened 2023-02-05 06:13 UTC
When I Compose a long post, and the new text reaches the bottom of the obvious window, it then goes behind the (photo, poll, CW) toolbar where it is hidden. Only scrolls up when a full line is hidden and another one begun in the hidden space. Happens with any keyboard of any height, follows the current height of an adjustable keyboard. If I manually drag the text up several lines, it pops back down behind the toolbar the next time it moves to a new line. Yes, it happens on the big iPad, too, though you really have to work to fill that window. 

Can't believe no one else is reporting this!

**Comment by ddimick** [comment] 2023-02-07 06:58
Is this a dupe of #337?

**Comment by Dimillian** [comment] 2023-02-07 06:59
THanks for for finding it, closing this one for now.

**Closed by Dimillian** 2023-02-07 06:59 UTC
Labels: bug
