### ISSUE TITLE
Bug: iPad - Settings Not Saving

### ISSUE THREAD

**Issue by sgclark** [Dimillian/IceCubesApp#295] opened 2023-01-22 22:21 UTC
1. When I select one of the choices to change the app icon on iPad, it does not change to that selection. It stays with the glass of ice cubes. In the app icon interface where all the choices are displayed, the alternative icon I chose has the green check. 

2.  When I make changes to Display colors on iPad, the changes save initially however if I go to another app on ipad and then go back to IceCubes, the theme/Display reverts back to the original colors (i.e. the purple in Ice Cubes-Dark) instead of what I selected (I.e. tint color = orange)

iPadOS 16.2 (20C65)
iPad Air 5th Gen.

**Comment by pimoore** [comment] 2023-01-23 00:38
I’m seeing this on iOS as well, latest version of 1.0.8

**Comment by pimoore** [comment] 2023-01-23 00:47
> 1. When I select one of the choices to change the app icon on iPad, it does not change to that selection. It stays with the glass of ice cubes. In the app icon interface where all the choices are displayed, the alternative icon I chose has the green check.
> 2. When I make changes to Display colors on iPad, the changes save initially however if I go to another app on ipad and then go back to IceCubes, the theme/Display reverts back to the original colors (i.e. the purple in Ice Cubes-Dark) instead of what I selected (I.e. tint color = orange)
> 
> iPadOS 16.2 (20C65) iPad Air 5th Gen.

For the theming issue, if “match system” Is enabled then turn that off before customizing. After doing that my changes are sticking after leaving and coming back to the app.

Cc: @Dimillian

**Comment by Dimillian** [comment] 2023-01-23 05:29
Yes thanks! Duplicate of another issue #277

**Closed by Dimillian** 2023-01-23 05:29 UTC
Labels: bug
