### ISSUE TITLE
Feature request: sync settings across devices via iCloud

### ISSUE THREAD

**Issue by saurabhsharan** [Dimillian/IceCubesApp#1167] opened 2023-03-04 19:24 UTC
I have IceCubes installed on 3 iOS devices. It would be great if settings I change on one device automatically sync to my other devices (e.g. switching IceCube's browser from the in-app browser to the system browser.)

**Comment by Dimillian** [comment] 2023-03-05 06:22
Duplicate of another one I can't find. It's planned at some point.

**Closed by Dimillian** 2023-03-05 06:22 UTC
Labels: enhancement
