### ISSUE TITLE
Bug: Notification tab icon shows unread counter after reading posts and then switching to Home

### ISSUE THREAD

**Issue by phpmacher** [Dimillian/IceCubesApp#857] opened 2023-02-14 13:37 UTC
## Environment:

 - OS: 16.3
 - IceCubesApp version: 1.4.8

## Description

If I am in the notification tab and have read all the posts and then switch to the home tab, the notification tab icon shows the number of previously unread posts.

Switching again removes the counter.

**Comment by Dimillian** [comment] 2023-02-16 07:36
Duplicate of #829

**Closed by Dimillian** 2023-02-16 07:36 UTC
Labels: bug
