### ISSUE TITLE
Feature request: an option to make custom colors themes, and be able to edit, rename and delete them.

### ISSUE THREAD

**Issue by recoveryawareness** [Dimillian/IceCubesApp#819] opened 2023-02-12 18:21 UTC
an option to make custom colors themes, and be able to edit, rename and delete them.

**Comment by pjolt** [comment] 2023-02-12 18:38
@recoveryawareness i noticed that this is a duplicate of your previous request #751 

Assuming this new request was created in error you could perhaps close this and leave the previous open to remove unneccesary duplicates.

**Comment by Dimillian** [comment] 2023-02-13 06:03
And it'll eventually come.

**Closed by Dimillian** 2023-02-13 06:03 UTC
Labels: enhancement
