### ISSUE TITLE
Feature request: create Threads

### ISSUE THREAD

**Issue by drohmd** [Dimillian/IceCubesApp#813] opened 2023-02-12 14:17 UTC
In Metatext, which I used before switching to IceCubes, I was able to write multiple toots at once by pressing a little + Symbol in the right corner when I am reaching the limit. 
I miss this feature sometimes and I have to reply manually. ![image](https://user-images.githubusercontent.com/120812779/218316379-d5425856-c67a-4b37-91f3-d93327048fba.jpeg)

**Comment by pjolt** [comment] 2023-02-12 17:54
Seems like duplicate of #156

**Closed** 2023-12-31 12:54 UTC
Labels: enhancement
