### ISSUE TITLE
Bug: reply button in the timeline doesn’t show the correct number of replies

### ISSUE THREAD

**Issue by nnmalex** [Dimillian/IceCubesApp#721] opened 2023-02-08 12:02 UTC
The reply button in the timeline doesn’t show the correct number of replies the toot has.
iOS v1.4.3

The button shows 0 for some toots that do have replies. When tapping on the toot the replies are loaded.

**Comment by phpmacher** [comment] 2023-02-08 13:15
Perhaps this is due to the distributed system that is the basis of Mastodon... more detailed informations could need more requests.

**Comment by nnmalex** [comment] 2023-02-08 13:41
Other clients on iOS show the count correctly at the exact same time.

**Comment by phpmacher** [comment] 2023-02-08 14:19
perhaps those clients do more background-requests?

**Comment by Dimillian** [comment] 2023-02-15 18:01
Duplicate of https://github.com/Dimillian/IceCubesApp/issues/889

**Closed by Dimillian** 2023-02-15 18:01 UTC
