### ISSUE TITLE
Bug:Can’t edit alt text on video; only delete the video

### ISSUE THREAD

**Issue by henrik** [Dimillian/IceCubesApp#213] opened 2023-01-21 08:50 UTC
I used the official client to make a toot including a video with an alt text: https://ruby.social/@henrik/109726283941427042

(I couldn’t upload a video or a GIF that kept its animation via Ice Cubes. That’s outside the scope of this ticket.)

If I edit this post in Ice Cubes and tap the “alt” badge, it only shows the option to delete the video. Either it requires more precision than I can achieve, or it’s impossible 😁

![98ADA982-FDB8-44FF-84A0-4C884D9B1238](https://user-images.githubusercontent.com/216/213859563-435f335f-e91d-46f8-a21d-16b14895ad84.jpeg)

Thank you again so much for your hard work on this app!

**Comment by Dimillian** [comment] 2023-01-21 10:45
I'm closing this as a duplicate of #154 as video support will be added a bit later, thanks!

**Closed by Dimillian** 2023-01-21 10:45 UTC
Labels: bug

**Comment by henrik** [comment] 2023-01-21 11:15
Sounds good! :)
