### ISSUE TITLE
Bug: Translate button shows up when there is no need

### ISSUE THREAD

**Issue by alakoring** [Dimillian/IceCubesApp#729] opened 2023-02-09 00:52 UTC
My system (iPadOS 16.3) is set to (American) English. But my own post is apparently considered to be in Norwegian — Ice Cubes 1.4.3 shows a translate button (see screen shot).

![IMG_0945](https://user-images.githubusercontent.com/12171257/217685672-6ef5f754-854f-4607-9874-5c17d1782016.jpeg)

I don’t know if this is an issue when posting or displaying. The post in question is https://mastodon.gamedev.place/@radiofreelunch/109831969145506013

Oh, and I just noticed that other posts in the thread are also considered to be in Norwegian? ![IMG_0946](https://user-images.githubusercontent.com/12171257/217686223-88361107-e4e8-4fe0-bc52-94dbdb3f8fae.PNG)

**Comment by Dimillian** [comment] 2023-02-09 17:55
This is duplicate of many other. Will see what can I do about this one but for now it's working like on the .social instance.

**Closed by Dimillian** 2023-02-09 17:55 UTC
Labels: bug

**Comment by alakoring** [comment] 2023-02-09 18:01
OK, I didn't find any other open issue. And not seeing any way to translate on the web for this post.

**Comment by Dimillian** [comment] 2023-02-09 18:28
Yes sorry, will consolidate all the talk there probably, even if it's not what the initial issue is about
