### ISSUE TITLE
Bug: Action icons not updating on Notifications list?

### ISSUE THREAD

**Issue by RobATX** [Dimillian/IceCubesApp#910] opened 2023-02-16 19:37 UTC
## Environment:

 - OS: 
  iOS 16.3.1
 - IceCubesApp version: 
  1.5.1

## Description

 I'm noticing that the Notificstions list is losing status on Faves and Boosts. See screenshots of Notification list which I just refreshed, and the underlying post. Is it a refresh issue? If I kill and reload the app, all is good. 

![image](https://user-images.githubusercontent.com/31712535/219469127-96000e79-f560-49a7-b1db-8059361547af.jpeg)
![image](https://user-images.githubusercontent.com/31712535/219469144-8748a2c3-ef10-44fe-8a31-7d53b60a5ac8.jpeg)

## Related Issues

 - [ ] Search that this bugs don't already exist before creating it.

**Comment by Dimillian** [comment] 2023-02-17 06:34
Duplicate of #889 will work on that later.

**Closed by Dimillian** 2023-02-17 06:34 UTC
Labels: bug
