### ISSUE TITLE
Feature request: Content filter

### ISSUE THREAD

**Issue by pacorob** [Dimillian/IceCubesApp#148] opened 2023-01-20 09:48 UTC
It would be great if a content filter would become available.

**Comment by Dimillian** [comment] 2023-01-20 11:19
duplicate of this #25

**Comment by pacorob** [comment] 2023-01-24 08:26
> duplicate of this #25

I'm wondering when looking at the other feature request #25 if this has actually been added to the app since I can't find such option nor was it listed in a recent app update. I'm talking about an actual custom content filter as is available in e.g. competitor apps like Mercury and Tusker as is also shown here: https://www.hardreset.info/devices/apps/apps-mastodon/add-new-filter/  
I therefore think this should be reopened.

**Comment by Dimillian** [comment] 2023-01-24 10:42
Right, it's indeed planned. I plan to rework the settings screen to have server side filter editable there per account.

**Comment by Dimillian** [comment] 2023-01-24 10:42
But it'll still duplicate of #115

**Closed by Dimillian** 2023-01-24 10:42 UTC
Labels: enhancement
