### ISSUE TITLE
Bug: sharing Videos from the Photos App not working

### ISSUE THREAD

**Issue by Apex-DE** [Dimillian/IceCubesApp#1923] opened 2024-01-24 05:56 UTC
## Environment:
 - OS: iOS 17.3
 - IceCubesApp version: 1.10.27

## Description

when selecting a video recorded with the iPhone and i try to share via the photos app and i select IceCubes as target, the IceCubes Post Composer opens and closes/crahses after about 2 seconds. Posting the video from within the App with the media selector works fine.
I can send a screen-video of the bug via mail for showing the bug in action.

**Comment by Dimillian** [comment] 2024-01-24 14:39
Yes because I cannot reproduce. How long is the video?

**Comment by Apex-DE** [comment] 2024-01-24 14:53
Hi,

it’s a short Video shot on iPhone14pro. Whats your Mail address?

Greetings

**Comment by Dimillian** [comment] 2024-01-24 14:57
hello@dimillian.app

**Comment by Dimillian** [comment] 2024-01-27 09:21
Fixed in next version, shipping soon

**Closed by Dimillian** 2024-01-27 09:21 UTC
Labels: bug

**Comment by Apex-DE** [comment] 2024-01-29 04:43
the issue got better with the fix, but it isn't gone. I have a 14mb sample for you to test, which still triggers the bug.
