### ISSUE TITLE
How do I scroll down through new messages? 

### ISSUE THREAD

**Issue by Gatobrit** [Dimillian/IceCubesApp#186] opened 2023-01-20 16:01 UTC
I'm a newbie. I'm enjoying Ice Cubes. 

When I open the app I see a number of new posts. Is there a way just to scroll through them oldest to newest? I can tap on the number of posts and go to the top of the timeline or hit the icon next to the number of posts to work through the new posts one by one.

Thanks!

**Comment by Dimillian** [comment] 2023-01-20 16:30
duplicate of #97 it'll be added at some point. Thanks!

**Closed by Dimillian** 2023-01-20 16:30 UTC
